### ISSUE TITLE
Simple Exception Raising

### ISSUE THREAD

**Issue by tavinus** [picqer/php-barcode-generator#42]
Hi,

I was testing my [tavinus/cli-barcode](https://github.com/tavinus/cli-barcode) script a bit and wanted to capture some simple errors.  
  
For example, if someone passes something that is not a number for a `CODE_128_C` barcode, PHP is gonna show Warning messages because we will be looping an array that does not exist:
```
PHP Warning:  Invalid argument supplied for foreach() in /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php on line 2820
Warning: Invalid argument supplied for foreach() in /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php on line 2820
```
However, it is gonna continue execution, and even generate an "empty" barcode sometimes.  
There is no way to identify this error when it happens.  
  
So by the warning messages I went to try and throw an Exception  
```
File:     picqer/php-barcode-generator/src/BarcodeGenerator.php
Line:     2815
Function: convertBarcodeArrayToNewStyle
```
Added: *(Please revise the Exception message)*
```php
if (empty($oldBarcodeArray['bcode'])) throw new \Exception("Could not process barcode! Seems like your barcode string is empty or invalid for the proposed format.");

```
Like This:
```php
    protected function convertBarcodeArrayToNewStyle($oldBarcodeArray)
    {
        if (empty($oldBarcodeArray['bcode'])) throw new \Exception("Could not process barcode! Seems like your barcode string is empty or invalid for the proposed format.");
        $newBarcodeArray = [];
        $newBarcodeArray['code'] = $oldBarcodeArray['code'];
        $newBarcodeArray['maxWidth'] = $oldBarcodeArray['maxw'];
        $newBarcodeArray['maxHeight'] = $oldBarcodeArray['maxh'];
        $newBarcodeArray['bars'] = [];
        foreach ($oldBarcodeArray['bcode'] as $oldbar) {
            $newBar = [];
            $newBar['width'] = $oldbar['w'];
            $newBar['height'] = $oldbar['h'];
            $newBar['positionVertical'] = $oldbar['p'];
            $newBar['drawBar'] = $oldbar['t'];
            $newBar['drawSpacing'] = ! $oldbar['t'];

            $newBarcodeArray['bars'][] = $newBar;
        }

        return $newBarcodeArray;
    }
```
Then you need to try and catch of course:
```php
// generate de barcode
try {
    $bc_data  = $generator->getBarcode($bc_string, $bc_type, $width, $height, $color);    
} catch (Exception $e) {
    echo "Error: ".$e->getMessage()."\n";
    exit(1);
}
```
Here it running:
```
$ barcode -e code_128_c -f SVG "1231241asdasb2" $HOME/teste.svg 
Error: Could not process barcode! Seems like your barcode string is invalid for the proposed format.
```
Here if it is not in "try/catch":
```
$ barcode -e code_128_c -f SVG "1231241asdasb2" $HOME/teste.svg 
PHP Fatal error:  Uncaught exception 'Exception' with message 'convertBarcodeArrayToNewStyle: Invalid Input Barcode! $oldBarcodeArray['bcode'] empty' in /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php:2815
Stack trace:
#0 /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php(182): Picqer\Barcode\BarcodeGenerator->convertBarcodeArrayToNewStyle(false)
#1 /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGeneratorSVG.php(21): Picqer\Barcode\BarcodeGenerator->getBarcodeData('1231241asdasb2', 'C128C')
#2 /mnt/dados/user/barcode/barcode.php(287): Picqer\Barcode\BarcodeGeneratorSVG->getBarcode('1231241asdasb2', 'C128C', 2, 30, '#000000')
#3 {main}
  thrown in /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php on line 2815
Fatal error: Uncaught exception 'Exception' with message 'convertBarcodeArrayToNewStyle: Invalid Input Barcode! $oldBarcodeArray['bcode'] empty' in /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php:2815
Stack trace:
#0 /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php(182): Picqer\Barcode\BarcodeGenerator->convertBarcodeArrayToNewStyle(false)
#1 /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGeneratorSVG.php(21): Picqer\Barcode\BarcodeGenerator->getBarcodeData('1231241asdasb2', 'C128C')
#2 /mnt/dados/user/barcode/barcode.php(287): Picqer\Barcode\BarcodeGeneratorSVG->getBarcode('1231241asdasb2', 'C128C', 2, 30, '#000000')
#3 {main}
  thrown in /mnt/dados/user/barcode/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php on line 2815
```
Prints heaps of stuff but should halt execution there anyways.  
Maybe you want to really create your Exception classes and make that stuff proper, but that is what I am using right now so I decided to post here.  

Maybe test with `is_array()` or `isset()`? Not sure.  
  
Thanks for this awesome code!  
  
Cheers!  
Gus  
  
PS: Maybe my little-script is useful to test your library in general.

**Comment by casperbakker** [comment]
Hi Gustavo,

Thanks for letting us know. It would certainly be better to show an exception for this situation. Regarding tests, we have unit tests for this library. When I come around to it, I will add the failing test and add the exceptions for this situation.

**Comment by casperbakker** [comment]
Added some testing to check for empty strings now.
